version: "3.8"

services:
  # Backend PHP + Apache
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./back:/var/www/html
    ports:
      - "8080:80"
    environment:
      DB_HOST: mariadb
      DB_NAME: ma_base
      DB_USER: user
      DB_PASS: userpass
    depends_on:
      - mariadb

  # Frontend React (dev server Vite)
  front:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./front:/app
      - front_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

  # Base de données
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ma_base
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - "8084:80"

  # Adminer
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8081:8080"

volumes:
  db_data:
  front_node_modules:
